# Fashion Mnist Dataset Classification using RESNET50

## Explaination of dataset

### It is a dataset comprised of 60,000 small square 28×28 pixel grayscale images of items of 10 types of clothing, such as shoes, t-shirts, dresses, and more. The mapping of all 0-9 integers to class labels is listed below.

* 0: T-shirt/top
* 1: Trouser
* 2: Pullover
* 3: Dress
* 4: Coat
* 5: Sandal
* 6: Shirt
* 7: Sneaker
* 8: Bag
* 9: Ankle boot


### Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
import tensorflow as tf

In [3]:
import keras

In [4]:
import cv2

In [5]:
from PIL import Image

In [6]:
from keras.layers import Flatten,Dense

In [56]:
from sklearn.metrics  import accuracy_score, f1_score

### Loading the training and test dataset

In [8]:
fashion_mnist=keras.datasets.fashion_mnist

In [9]:
(x_train,y_train),(x_test,y_test)=fashion_mnist.load_data()

In [12]:
x_train.shape

(60000, 28, 28)

In [13]:
X_train = np.zeros((len(x_train) ,64, 64, 3))

In [14]:
# We are performing two steps here :
# 1. Converting the imag from grayscale to RGB
# 2. Resizing the image to 64x64 from 28x28 because the minimum support size for an image in RESNET model is 32x32

for i,x in enumerate(x_train):
    im = Image.fromarray(x_train[i]).convert('RGB')
    arr = np.array(im.resize((64,64)))
    X_train[i] = arr

In [15]:
# We are using for loops in order to view all of the X_train[0]

for i in X_train[0]:
    print(i)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0

 [  0.   0.   0.]]
[[  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [ 68.  68.  68.]
 [161. 161. 161.]
 [208. 208. 208.]
 [222. 222. 222.]
 [227. 227. 227.]
 [221. 221. 221.]
 [216. 216. 216.]
 [216. 216. 216.]
 [219. 219. 219.]
 [219. 219. 219.]
 [219. 219. 219.]
 [219. 219. 219.]
 [219. 219. 219.]
 [220. 220. 220.]
 [221. 221. 221.]
 [222. 222. 222.]
 [221. 221. 221.]
 [220. 220. 220.]
 [220. 220. 220.]
 [219. 219. 219.]
 [219. 219. 219.]
 [222. 222. 222.]
 [225. 225. 225.]
 [227. 227. 227.]
 [229. 229. 229.]
 [229. 22

Rationalizing the dataset

In [15]:
X_train = X_train/255

In [16]:
for i in X_train[0]:
    print(i)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0

In [17]:
X_train[0].shape

(64, 64, 3)

#### The next step is to create model using RESNET50 that suit our needs

In [19]:
resnet_Model = tf.keras.applications.ResNet50(
    include_top=False,
    weights="imagenet",
    input_shape=(64,64,3),
    pooling='avg',
    classes=10,
)

In [21]:
# Making the already trained ResNet layes non trainable again

for layer in resnet_Model.layers:
    layer.trainable=False

In [22]:
my_model = keras.Sequential() # Initializing a sequential keras model 

In [23]:
my_model.add(resnet_Model) # Adding the ResNet layer to our mode

In [24]:
# Adding the other necessary layers

my_model.add(Flatten())
my_model.add(Dense(512,activation='relu'))
my_model.add(Dense(10,activation='softmax'))

In [25]:
my_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 resnet50 (Functional)       (None, 2048)              23587712  
                                                                 
 flatten (Flatten)           (None, 2048)              0         
                                                                 
 dense (Dense)               (None, 512)               1049088   
                                                                 
 dense_1 (Dense)             (None, 10)                5130      
                                                                 
Total params: 24,641,930
Trainable params: 1,054,218
Non-trainable params: 23,587,712
_________________________________________________________________


In [26]:
my_model.compile(optimizer=keras.optimizers.Adam(learning_rate= 1e-4),
loss='sparse_categorical_crossentropy',
metrics=['accuracy'])

In [27]:
my_model.fit(X_train,y_train, epochs = 3)

Epoch 1/3
1875/1875 [==============================] - 339s 178ms/step - loss: 1.2705 - accuracy: 0.6096
Epoch 2/3
1875/1875 [==============================] - 347s 185ms/step - loss: 0.8273 - accuracy: 0.7233
Epoch 3/3
1875/1875 [==============================] - 343s 183ms/step - loss: 0.7140 - accuracy: 0.7526


#### Now its time for the model to generate some predictions

In [28]:
X_test = np.zeros((len(x_test) ,64, 64, 3))

In [29]:
for i,x in enumerate(x_test):
    im = Image.fromarray(x_test[i]).convert('RGB')
    arr = np.array(im.resize((64,64)))
    X_test[i] = arr

In [30]:
X_test = X_test/255

In [39]:
y_pred = my_model.predict(X_test)

313/313 [==============================] - 51s 164ms/step


In [40]:
y_pred.shape

(10000, 10)

In [41]:
y_pred[0]

array([1.5348297e-03, 4.6105546e-05, 9.5727626e-04, 2.3475008e-04,
       6.8189896e-05, 6.9806665e-02, 6.1655871e-04, 1.1128268e-01,
       4.5631561e-02, 7.6982135e-01], dtype=float32)

In [42]:
Y_pred =  np.zeros(len(y_pred))

In [44]:
for i in range(len(y_pred)):
    Y_pred[i] = np.argmax(y_pred[i])

In [46]:
len(Y_pred)

10000

In [55]:
print("The accuracy of our model is : " , accuracy_score(y_test , Y_pred) * 100 ,  "%")

The accuracy of our model is :  74.26 %
